spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transport
    username: agermenos
    password:
    driver-class-name: org.postgresql.Driver
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: create


logging:
  level:
    org.springframework: INFO
    org.hibernate: DEBUG
    {main package path}: INFO